// Date: 27/10/2014 22:27:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer TopFront;
    ModelRenderer TopLeft;
    ModelRenderer TopBack;
    ModelRenderer VeryBottom;
    ModelRenderer BottomInside;
    ModelRenderer SideFront;
    ModelRenderer SideBack;
    ModelRenderer SideRight;
    ModelRenderer SideLeft;
    ModelRenderer TopRight;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      TopFront = new ModelRenderer(this, 34, 62);
      TopFront.addBox(0F, 0F, 0F, 14, 1, 1);
      TopFront.setRotationPoint(-7F, 8F, -7F);
      TopFront.setTextureSize(64, 64);
      TopFront.mirror = true;
      setRotation(TopFront, 0F, 0F, 0F);
      TopLeft = new ModelRenderer(this, 0, 51);
      TopLeft.addBox(0F, 0F, 0F, 1, 1, 12);
      TopLeft.setRotationPoint(6F, 8F, -6F);
      TopLeft.setTextureSize(64, 64);
      TopLeft.mirror = true;
      setRotation(TopLeft, 0F, 0F, 0F);
      TopBack = new ModelRenderer(this, 34, 62);
      TopBack.addBox(0F, 0F, 0F, 14, 1, 1);
      TopBack.setRotationPoint(-7F, 8F, 6F);
      TopBack.setTextureSize(64, 64);
      TopBack.mirror = true;
      setRotation(TopBack, 0F, 0F, 0F);
      VeryBottom = new ModelRenderer(this, 0, 0);
      VeryBottom.addBox(0F, 0F, 0F, 12, 1, 12);
      VeryBottom.setRotationPoint(-6F, 23F, -6F);
      VeryBottom.setTextureSize(64, 64);
      VeryBottom.mirror = true;
      setRotation(VeryBottom, 0F, 0F, 0F);
      BottomInside = new ModelRenderer(this, 0, 13);
      BottomInside.addBox(0F, 0F, 0F, 14, 1, 14);
      BottomInside.setRotationPoint(-7F, 22F, -7F);
      BottomInside.setTextureSize(64, 64);
      BottomInside.mirror = true;
      setRotation(BottomInside, 0F, 0F, 0F);
      SideFront = new ModelRenderer(this, 0, 28);
      SideFront.addBox(0F, 0F, 0F, 16, 13, 1);
      SideFront.setRotationPoint(-8F, 9F, -8F);
      SideFront.setTextureSize(64, 64);
      SideFront.mirror = true;
      setRotation(SideFront, 0F, 0F, 0F);
      SideBack = new ModelRenderer(this, 0, 28);
      SideBack.addBox(0F, 0F, 0F, 16, 13, 1);
      SideBack.setRotationPoint(-8F, 9F, 7F);
      SideBack.setTextureSize(64, 64);
      SideBack.mirror = true;
      setRotation(SideBack, 0F, 0F, 0F);
      SideRight = new ModelRenderer(this, 34, 28);
      SideRight.addBox(0F, 0F, 0F, 1, 13, 14);
      SideRight.setRotationPoint(-8F, 9F, -7F);
      SideRight.setTextureSize(64, 64);
      SideRight.mirror = true;
      setRotation(SideRight, 0F, 0F, 0F);
      SideLeft = new ModelRenderer(this, 34, 28);
      SideLeft.addBox(0F, 0F, 0F, 1, 13, 14);
      SideLeft.setRotationPoint(7F, 9F, -7F);
      SideLeft.setTextureSize(64, 64);
      SideLeft.mirror = true;
      setRotation(SideLeft, 0F, 0F, 0F);
      TopRight = new ModelRenderer(this, 0, 51);
      TopRight.addBox(0F, 0F, 0F, 1, 1, 12);
      TopRight.setRotationPoint(-7F, 8F, -6F);
      TopRight.setTextureSize(64, 64);
      TopRight.mirror = true;
      setRotation(TopRight, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TopFront.render(f5);
    TopLeft.render(f5);
    TopBack.render(f5);
    VeryBottom.render(f5);
    BottomInside.render(f5);
    SideFront.render(f5);
    SideBack.render(f5);
    SideRight.render(f5);
    SideLeft.render(f5);
    TopRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
