// Date: 9-2-2015 17:09:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer BottomLeft;
    ModelRenderer VeryBottom;
    ModelRenderer Front;
    ModelRenderer Back;
    ModelRenderer Left;
    ModelRenderer Right;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Base;
    ModelRenderer Handle;
    ModelRenderer PressPlate;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BottomLeft = new ModelRenderer(this, 0, 13);
      BottomLeft.addBox(0F, 0F, 0F, 14, 1, 14);
      BottomLeft.setRotationPoint(-7F, 22F, -7F);
      BottomLeft.setTextureSize(64, 32);
      BottomLeft.mirror = true;
      setRotation(BottomLeft, 0F, 0F, 0F);
      VeryBottom = new ModelRenderer(this, 0, 0);
      VeryBottom.addBox(0F, 0F, 0F, 12, 1, 12);
      VeryBottom.setRotationPoint(-6F, 23F, -6F);
      VeryBottom.setTextureSize(64, 32);
      VeryBottom.mirror = true;
      setRotation(VeryBottom, 0F, 0F, 0F);
      Front = new ModelRenderer(this, 0, 28);
      Front.addBox(0F, 0F, 0F, 16, 8, 1);
      Front.setRotationPoint(-8F, 14F, -8F);
      Front.setTextureSize(64, 32);
      Front.mirror = true;
      setRotation(Front, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 0, 28);
      Back.addBox(0F, 0F, 0F, 16, 8, 1);
      Back.setRotationPoint(-8F, 14F, 7F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Left = new ModelRenderer(this, 0, 42);
      Left.addBox(0F, 0F, 0F, 1, 8, 14);
      Left.setRotationPoint(-8F, 14F, -7F);
      Left.setTextureSize(64, 32);
      Left.mirror = true;
      setRotation(Left, 0F, 0F, 0F);
      Right = new ModelRenderer(this, 0, 42);
      Right.addBox(0F, 0F, 0F, 1, 8, 14);
      Right.setRotationPoint(7F, 14F, -7F);
      Right.setTextureSize(64, 32);
      Right.mirror = true;
      setRotation(Right, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 34, 28);
      Shape1.addBox(0F, 0F, 0F, 1, 1, 7);
      Shape1.setRotationPoint(-0.5F, 9F, -8F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 8, 37);
      Shape2.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape2.setRotationPoint(-2F, 9F, 7F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 8, 37);
      Shape3.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape3.setRotationPoint(-2F, 9F, -8F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 30, 58);
      Shape4.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape4.setRotationPoint(-2F, 9F, 7F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 30, 58);
      Shape5.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape5.setRotationPoint(1F, 9F, 7F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 30, 47);
      Shape6.addBox(0F, 0F, 0F, 1, 1, 3);
      Shape6.setRotationPoint(-1.5F, 9F, -1.5F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 34, 28);
      Shape7.addBox(0F, 0F, 0F, 1, 1, 7);
      Shape7.setRotationPoint(-0.5F, 9F, 1F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 30, 47);
      Shape8.addBox(0F, 0F, 0F, 1, 1, 3);
      Shape8.setRotationPoint(0.5F, 9F, -1.5F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 37);
      Shape9.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape9.setRotationPoint(-1.5F, 9F, -1.5F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 37);
      Shape10.addBox(0F, 0F, 0F, 3, 1, 1);
      Shape10.setRotationPoint(-1.5F, 9F, 0.5F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 30, 58);
      Shape11.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape11.setRotationPoint(-2F, 9F, -8F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 30, 58);
      Shape12.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape12.setRotationPoint(1F, 9F, -8F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 48, 0);
      Base.addBox(0F, 0F, 0F, 1, 8, 1);
      Base.setRotationPoint(-0.5F, 8F, -0.5F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Handle = new ModelRenderer(this, 0, 39);
      Handle.addBox(0F, 0F, 0F, 7, 1, 1);
      Handle.setRotationPoint(-3.5F, 8F, -0.5F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      PressPlate = new ModelRenderer(this, 0, 13);
      PressPlate.addBox(0F, 0F, 0F, 14, 1, 14);
      PressPlate.setRotationPoint(-7F, 16F, -7F);
      PressPlate.setTextureSize(64, 32);
      PressPlate.mirror = true;
      setRotation(PressPlate, 0.0174533F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    BottomLeft.render(f5);
    VeryBottom.render(f5);
    Front.render(f5);
    Back.render(f5);
    Left.render(f5);
    Right.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Base.render(f5);
    Handle.render(f5);
    PressPlate.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
